#!/bin/bash
awk '
/      \{\/\* PROMISE TO PAY CREATION FORM MODAL \*\/\}/ {
    print "      {activeTab === '"'Profile'"' && ("
    print "        <div className=\"space-y-6\">"
    print "          <div className=\"bg-white border border-stone-200 p-6 rounded-3xl space-y-6\">"
    print "            <div className=\"flex items-center justify-between border-b border-stone-100 pb-3\">"
    print "              <div className=\"flex items-center space-x-2.5\">"
    print "                <User className=\"text-[#1B4332] w-5 h-5\" />"
    print "                <h3 className=\"font-display font-black text-[#1B4332] uppercase text-sm\">Profile Status</h3>"
    print "              </div>"
    print "            </div>"
    print "            <div className=\"space-y-4\">"
    print "              <div className=\"flex justify-between items-end\">"
    print "                <div>"
    print "                  <span className=\"text-xs font-bold text-stone-600 block mb-1\">Profile Completion</span>"
    print "                  <span className=\"text-2xl font-black font-display text-[#1B4332]\">85%</span>"
    print "                </div>"
    print "                <span className=\"text-[10px] uppercase font-mono tracking-widest text-[#2D6A4F] bg-emerald-50 px-2 py-1 rounded-lg border border-emerald-100 font-bold\">Almost Complete</span>"
    print "              </div>"
    print "              <div className=\"w-full bg-stone-100 h-3 rounded-full overflow-hidden border border-stone-200/50\">"
    print "                <div className=\"bg-[#2D6A4F] h-full rounded-full transition-all duration-500 shadow-sm\" style={{ width: \"85%\" }}></div>"
    print "              </div>"
    print "              <div className=\"space-y-2 mt-4 pt-4 border-t border-stone-100\">"
    print "                 <div className=\"flex items-center space-x-3 bg-stone-50 p-2.5 rounded-xl border border-stone-100\">"
    print "                   <CheckCircle className=\"w-4 h-4 text-emerald-600\" />"
    print "                   <span className=\"text-xs text-stone-700 font-bold\">Identity Verified</span>"
    print "                 </div>"
    print "                 <div className=\"flex items-center space-x-3 bg-stone-50 p-2.5 rounded-xl border border-stone-100\">"
    print "                   <CheckCircle className=\"w-4 h-4 text-emerald-600\" />"
    print "                   <span className=\"text-xs text-stone-700 font-bold\">Guarantor Added</span>"
    print "                 </div>"
    print "                 <div className=\"flex items-center space-x-3 bg-stone-50 p-2.5 rounded-xl border border-stone-100\">"
    print "                   <CheckCircle className=\"w-4 h-4 text-emerald-600\" />"
    print "                   <span className=\"text-xs text-stone-700 font-bold\">Work References Uploaded</span>"
    print "                 </div>"
    print "                 <div className=\"flex items-center space-x-3 bg-amber-50 p-2.5 rounded-xl border border-amber-200 cursor-pointer hover:bg-amber-100 transition\">"
    print "                   <div className=\"w-4 h-4 rounded-full border-2 border-amber-500 shrink-0\"></div>"
    print "                   <div className=\"flex justify-between w-full items-center\">"
    print "                     <span className=\"text-xs text-amber-900 font-bold\">Add Emergency Contact</span>"
    print "                     <span className=\"text-[9px] uppercase font-mono text-amber-700 bg-white px-2 py-0.5 rounded shadow-sm\">Action Required</span>"
    print "                   </div>"
    print "                 </div>"
    print "              </div>"
    print "            </div>"
    print "          </div>"
    print "        </div>"
    print "      )}"
    print ""
    print "      {/* PROMISE TO PAY CREATION FORM MODAL */}"
    next
}
{ print }
' src/components/dashboards/TenantDashboard.tsx > temp.tsx && mv temp.tsx src/components/dashboards/TenantDashboard.tsx
