#!/bin/bash
awk '
/\{activeTab === '"'Services'"' && \(/ {
    print
    print "        <div className=\"space-y-6\">"
    print "          <div className=\"flex justify-between items-end\">"
    print "             <div>"
    print "               <h2 className=\"font-display font-black text-[#1B4332] uppercase text-lg\">Charges and Levies</h2>"
    print "               <p className=\"text-xs text-stone-500\">Real-time status of all your service charges.</p>"
    print "             </div>"
    print "             <div className=\"flex gap-2\">"
    print "               <button onClick={() => triggerSuccess(\"Exporting Service Charge Ledger as CSV...\")} className=\"px-3 py-1.5 border border-stone-200 bg-white hover:bg-stone-50 text-stone-600 rounded-lg text-[10px] font-bold uppercase transition flex items-center space-x-1\">"
    print "                 <Download className=\"w-3 h-3\" /><span>CSV</span>"
    print "               </button>"
    print "               <button onClick={() => triggerSuccess(\"Exporting Service Charge Ledger as PDF...\")} className=\"px-3 py-1.5 border border-stone-200 bg-white hover:bg-stone-50 text-stone-600 rounded-lg text-[10px] font-bold uppercase transition flex items-center space-x-1\">"
    print "                 <Download className=\"w-3 h-3\" /><span>PDF</span>"
    print "               </button>"
    print "             </div>"
    print "          </div>"
    print ""
    print "          <div className=\"space-y-4\">"
    print "            {serviceCharges.map((sc, idx) => ("
    print "              <div key={idx} className={`bg-white border p-5 rounded-3xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4 ${"
    print "                sc.status === \"Unpaid\" ? \"border-l-4 border-l-red-500 border-stone-200\" : "
    print "                sc.status === \"Pending Verification\" ? \"border-l-4 border-l-amber-500 border-stone-200\" :"
    print "                \"border-l-4 border-l-emerald-500 border-stone-200\""
    print "              }`}>"
    print "                <div>"
    print "                  <h4 className=\"font-display font-black text-stone-800 text-sm\">{sc.name}</h4>"
    print "                  <div className=\"flex items-center space-x-2 mt-1\">"
    print "                    <strong className=\"text-[#1B4332] font-mono text-sm\">₦{sc.amount.toLocaleString()}</strong>"
    print "                    <span className=\"text-[10px] text-stone-400 font-mono\">{sc.frequency}</span>"
    print "                  </div>"
    print "                  <span className=\"block text-[10px] text-stone-500 mt-2 font-mono\">Due: {sc.dueDate}</span>"
    print "                </div>"
    print "                <div className=\"flex flex-col items-end shrink-0 space-y-2\">"
    print "                  {sc.status === \"Unpaid\" && ("
    print "                     <div className=\"flex items-center space-x-3\">"
    print "                       <span className=\"text-red-600 font-black font-display uppercase tracking-wider\">UNPAID</span>"
    print "                       <strong className=\"text-red-600 font-mono\">₦{sc.amount.toLocaleString()}</strong>"
    print "                     </div>"
    print "                  )}"
    print "                  {sc.status === \"Unpaid\" && ("
    print "                     <button "
    print "                       onClick={() => { setReceiptUploadCharge({name: sc.name, amount: sc.amount}); setActiveTab(\"Payments\"); addToRecentlyViewed({ id: sc.id, type: \"Service Charge\", name: sc.name, time: \"Just now\", icon: DollarSign }); }}"
    print "                       className=\"px-5 py-2 bg-[#2D6A4F] hover:bg-[#1B4332] text-white rounded-xl text-xs font-bold uppercase transition shadow-md\""
    print "                     >Pay Now</button>"
    print "                  )}"
    print "                  {sc.status === \"Pending Verification\" && ("
    print "                     <div className=\"flex flex-col items-end\">"
    print "                       <span className=\"text-amber-500 font-black font-display uppercase tracking-wider\">PENDING VERIFICATION</span>"
    print "                       <span className=\"text-stone-400 text-[10px] font-mono mt-1\">Receipt Uploaded on {sc.verificationDate}</span>"
    print "                     </div>"
    print "                  )}"
    print "                  {sc.status === \"Paid\" && ("
    print "                     <div className=\"flex items-center space-x-3\">"
    print "                       <span className=\"text-emerald-600 font-black font-display uppercase tracking-wider\">PAID</span>"
    print "                       <span className=\"text-emerald-700 text-xs font-mono font-bold bg-emerald-50 px-2 py-0.5 rounded-md\">Paid {sc.verificationDate}</span>"
    print "                     </div>"
    print "                  )}"
    print "                </div>"
    print "              </div>"
    print "            ))}"
    print "          </div>"
    print "          "
    print "          {/* SUMMARY LINE */}"
    print "          {serviceCharges.some(sc => sc.status !== \"Paid\") ? ("
    print "             <div className=\"bg-amber-50 border border-amber-200 p-4 rounded-2xl flex justify-between items-center\">"
    print "               <span className=\"text-amber-800 text-xs font-bold uppercase tracking-wider\">Total Outstanding</span>"
    print "               <strong className=\"text-amber-900 font-mono text-base\">₦{serviceCharges.filter(sc => sc.status !== \"Paid\").reduce((acc, curr) => acc + curr.amount, 0).toLocaleString()} across {serviceCharges.filter(sc => sc.status !== \"Paid\").length} charges</strong>"
    print "             </div>"
    print "          ) : ("
    print "             <div className=\"bg-emerald-50 border border-emerald-200 p-4 rounded-2xl flex items-center space-x-3 justify-center text-emerald-800\">"
    print "               <CheckCircle className=\"w-5 h-5\" />"
    print "               <span className=\"font-bold text-sm uppercase tracking-wider\">All Charges Cleared for This Period</span>"
    print "             </div>"
    print "          )}"
    print "        </div>"
    print "      )}"
    in_services = 1
    next
}
in_services {
    if (/^      \{activeTab === '"'Support'"' && \(/) {
        in_services = 0
        print
    }
    next
}
{ print }
' src/components/dashboards/TenantDashboard.tsx > temp.tsx && mv temp.tsx src/components/dashboards/TenantDashboard.tsx
