#!/bin/bash
awk '
/      \{activeTab === '"'Payments'"' && \(/ {
    print "          {/* RECENTLY VIEWED & ANNOUNCEMENTS */}"
    print "          <div className=\"space-y-6 pt-4\">"
    print "            <div>"
    print "              <div className=\"flex items-center space-x-2.5 border-b border-stone-100 pb-3 mb-4\">"
    print "                <Clock className=\"text-stone-400 w-4 h-4\" />"
    print "                <h3 className=\"font-display font-black text-stone-600 uppercase text-xs tracking-wider\">Recently Viewed</h3>"
    print "              </div>"
    print "              <div className=\"flex overflow-x-auto gap-4 pb-2 snap-x\">"
    print "                {recentlyViewed.length > 0 ? recentlyViewed.map((item, idx) => ("
    print "                  <div key={idx} className=\"shrink-0 w-48 p-4 bg-white border border-stone-200 rounded-2xl flex flex-col items-center justify-center text-center cursor-pointer hover:border-stone-400 transition snap-start\">"
    print "                    <div className=\"w-8 h-8 rounded-full bg-stone-50 border border-stone-100 flex items-center justify-center mb-2\">"
    print "                       <Activity className=\"w-4 h-4 text-stone-500\" />"
    print "                    </div>"
    print "                    <span className=\"font-bold text-xs text-stone-800 line-clamp-1\">{item.name}</span>"
    print "                    <span className=\"text-[9px] font-mono text-stone-400 mt-1 uppercase\">{item.type}</span>"
    print "                  </div>"
    print "                )) : ("
    print "                  <div className=\"w-full p-4 bg-stone-50 rounded-2xl border border-stone-100 text-center text-xs text-stone-500\">No recently viewed items.</div>"
    print "                )}"
    print "              </div>"
    print "            </div>"
    print ""
    print "            <div>"
    print "              <div className=\"flex items-center space-x-2.5 border-b border-stone-100 pb-3 mb-4\">"
    print "                <Bell className=\"text-[#1B4332] w-4 h-4\" />"
    print "                <h3 className=\"font-display font-black text-[#1B4332] uppercase text-xs tracking-wider\">Platform Announcements</h3>"
    print "              </div>"
    print "              <div className=\"space-y-3\">"
    print "                {announcements.map((ann, idx) => ("
    print "                  <div key={idx} className=\"bg-stone-50 border border-stone-200 p-4 rounded-2xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4 group\">"
    print "                    <div>"
    print "                      <h4 className=\"font-bold text-stone-800 text-sm\">{ann.title}</h4>"
    print "                      <p className=\"text-stone-600 text-xs mt-1 leading-relaxed\">{ann.body}</p>"
    print "                      <span className=\"text-[10px] font-mono text-stone-400 mt-2 block\">{ann.date}</span>"
    print "                    </div>"
    print "                    <button onClick={() => setAnnouncements(announcements.filter(a => a.id !== ann.id))} className=\"shrink-0 px-3 py-1.5 bg-white border border-stone-200 text-stone-500 rounded-lg text-[9px] font-bold uppercase hover:bg-stone-100 transition\">Dismiss</button>"
    print "                  </div>"
    print "                ))}"
    print "                {announcements.length === 0 && <div className=\"text-xs text-stone-500 font-mono\">No new announcements.</div>}"
    print "              </div>"
    print "            </div>"
    print "          </div>"
    print "        </div>"
    print "      )}"
    print ""
    print "      {activeTab === 'Payments' && ("
    next
}
{ print }
' src/components/dashboards/TenantDashboard.tsx > temp.tsx && mv temp.tsx src/components/dashboards/TenantDashboard.tsx
